block-beta
  columns 3
  space A(("&nbsp;<br/>01<br/>&nbsp;&nbsp;Publish evidence&nbsp;&nbsp;<br/>&nbsp;")) space
  D(("&nbsp;<br/>04<br/>&nbsp;&nbsp;Measure outcomes&nbsp;&nbsp;<br/>&nbsp;")) H(("&nbsp;<br/>&nbsp;&nbsp;AUTHORITY&nbsp;&nbsp;<br/>&nbsp;&nbsp;FLYWHEEL&nbsp;&nbsp;<br/>&nbsp;")) B(("&nbsp;<br/>02<br/>&nbsp;&nbsp;Earn references&nbsp;&nbsp;<br/>&nbsp;"))
  space C(("&nbsp;<br/>03<br/>&nbsp;&nbsp;Gain visibility&nbsp;&nbsp;<br/>&nbsp;")) space
  A --> B
  B --> C
  C --> D
  D -.-> A
  style H fill:#10282d,stroke:#1df9f8,stroke-width:3px
  style A fill:#111827,stroke:#1f8f95,stroke-width:2px
  style B fill:#111827,stroke:#1f8f95,stroke-width:2px
  style C fill:#111827,stroke:#1f8f95,stroke-width:2px
  style D fill:#111827,stroke:#1f8f95,stroke-width:2px
